2018-09-21 17:34:33 [ERROR] : str: data/directories.dat is not a file  in /usr/local/lib/python3.6/dist-packages/opendoor-3.4.481-py3.6.egg/src/lib/package/exceptions.py -> __init__() line 26
2018-09-21 17:34:38 [ERROR] : str: data/directories.dat is not a file  in /usr/local/lib/python3.6/dist-packages/opendoor-3.4.481-py3.6.egg/src/lib/package/exceptions.py -> __init__() line 26
2018-09-21 17:35:33 [ERROR] : str: data/directories.dat is not a file  in /usr/local/lib/python3.6/dist-packages/opendoor-3.4.481-py3.6.egg/src/lib/package/exceptions.py -> __init__() line 26
